### ISSUE TITLE
[Textile] Links on issue's description is not correctly displayed.

### ISSUE THREAD

**Issue by Jdecaudin** [altsol/redmine_mattermost#23]
When I create a Redmine issue with a description like : 
```
Search on "Google":https://www.google.com
```
that uses [Textile links](http://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingTextile#External-links).
Mattermost does not display "Google" with a link on it, but the string `"Google":https://www.google.com`

**Comment by thanosk** [comment]
Hello, I took my time to do a little research on this. 

Have you tried using Markdown text formatting in Redmine? You can switch in Redmine via Administration -> Settings -> Text formatting -> Markdown.

Since Mattermost natively supports markdown, turning Redmine to Markdown is expected to produce the best results. The only disadvantage of this is in case you have a large Redmine installation and are sceptical on how to handle your old context stored in Textile.

On the other hand, it is feasible to include a small parser in this plugin, so that when Redmine uses Textile, this plugin converts to Markdown and then feeds it to Mattermost. I'll try to bring this feature in the future.

**Comment by Jdecaudin** [comment]
Thank you !
The text formating solution seems to be good. And the Textile parser is a plus.
