### ISSUE TITLE
Incorrect url with reverse proxy

### ISSUE THREAD

**Issue by skinner33** [altsol/redmine_mattermost#4]
Hi,

I'm having a setup where redmine is reachable via example.com/redmine. A reverse proxy sends the requests to a redmine instance where redmine is served in /.
While redmine itself works correctly, and the links in the emails are correct, the urls generated by this plugin look like example.com/redmine/redmine.

So, if a generated a new issue, I get an e-mail with the link example.com/redmine/issues/1, which is correct and expected. The mattermost messages has linked example.com/redmine/redmine/issues/1 which does not work.

**Comment by thanosk** [comment]
@skinner33 I'm not experiencing it, but I can understand the problem. I've done a little digging in Redmine's issues and came up with [Defect 20192](http://www.redmine.org/issues/20192). This also shows what Rails code Redmine itself is using for avoiding the issue when e-mailing notifications.

I could try to use or mimic the same code in this plugin, but I'll need some time for setting up a similar sub-uri proxy configuration in order to do proper testing (if you happen to have it Docker-ized or are willing/able to experiment with Rails/Ruby code, it would help).

Can you experiment a bit with the proxy configuration? It might be possible to work around it by changing proxying method, take a look at [this guide](http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI). Lastly, can you ensure that your "Host name and path" setting (in Redmine Administration Settings / General tab) is properly configured? Can you try it with or without including the sub-uri to check if it changes anything?

**Comment by skinner33** [comment]
Hi!

> I could try to use or mimic the same code in this plugin, but I'll need
> some time for setting up a similar sub-uri proxy configuration in order
> to do proper testing (if you happen to have it Docker-ized or are
> willing/able to experiment with Rails/Ruby code, it would help).

I'm using the docker-image by sameersbn
https://github.com/sameersbn/docker-redmine. I can try some code, but
I'm far from fluent in ruby.

> Lastly, can you ensure that your "Host name and path" setting (in
> Redmine Administration Settings / General tab) is properly configured?
> Can you try it with or without including the sub-uri to check if it
> changes anything?

Yes, I can confirm that this was set correctly. Luckily, by removing the
sub-uri, both, the e-mails and the mattermost messages seam to have a
correct URL. I'm not sure if this has other side-effects, so this may
only be a workaround and not a fix ..

**Comment by thanosk** [comment]
Thank you for your feedback, it already helps! If there are no side-effects, you can work this way until I set everything up and test if borrowing the source code from mailer.rb achieves what I expect, which is making no difference how "host name and path" is configured.

**Comment by thanosk** [comment]
@skinner33 hi again, I think I've solved it, can you pull the newest plugin version, revert your configuration back to its original value, restart your redmine (optionally, but just to be sure), and confirm it's working ok, please?

**Comment by skinner33** [comment]
Hi,

I've performed the update and I can confirm that the update resolved this issue.

Thanks!
